config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:new, :create, :show, :index] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: {
    scope: [ :list_id ]
  }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/2128042/pexels-photo-2128042.jpeg);">
  <div class="container">
    <h1>Let's watch some movies</h1>
  </div>
</div>
<div class="container mt-3">
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('https://ducunl0s4svtl.cloudfront.net/wp-content/uploads/2017/10/flat-clapperboard-icon_1063-38.jpg') %>)">
        <%= link_to "#{list.name}", list_path(list), class: 'text-decoration-none text-white' %>
      </div>
    <% end %>
  </div>
  <%= link_to "Create a list", new_list_path, class: 'btn btn-warning text-decoration-none mt-3 mb-3' %>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <h1>New List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
  <%= link_to "Back to list", lists_path  %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : image_path('https://ducunl0s4svtl.cloudfront.net/wp-content/uploads/2017/10/flat-clapperboard-icon_1063-38.jpg') %>)">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>
<div class="container mt-3 mb-3">
  <h3>Movies:</h3>
  <div class="row">
    <div class="col-9">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card-product mb-3">
          <%= image_tag bookmark.movie.poster_url, width: 200 %>
          <div class="card-product-infos">
            <h2><%= bookmark.movie.title %></h2>
            <p>"<%= bookmark.comment %>" <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Delete bookmark?" } do %>
                <i class="fa-solid fa-delete-left"></i>
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-3">
      <div class="sticky-top border shadow p-3">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment %>
          <%= f.association :movie %>
          <%= f.submit "Add Movie", class: 'btn btn-warning' %>
        <% end %>
      </div>
    </div>
  </div>
  <%= link_to "Back to home", lists_path, class: 'btn btn-warning text-decoration-none mt-3' %>
</div>